podman-compose up -d --force-recreate --build
podman image tag localhost/supper-searchbot_executor hungnguyen991995/supper-search
podman image push hungnguyen991995/supper-search
set /p DUMMY=Hit ENTER to continue...
podman-compose down -v
set /p DUMMY=Hit ENTER to continue...